FROM node:22-alpine

RUN apk add --no-cache dumb-init

WORKDIR /app
ENV CI=1

RUN corepack enable && corepack prepare pnpm@12.4.2 --activate

COPY . .
RUN pnpm install --frozen-lockfile

ENTRYPOINT ["/usr/bin/dumb-init","--"]
CMD ["pnpm","--filter","@3aksa/api","start"]
